services:
  bill_nav:
    image: bill_nav
    container_name: bill_nav

    working_dir: /bill_nav

    tty: true
    stdin_open: true
    privileged: true

    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/snd:/dev/snd"
      - "/dev/dri:/dev/dri"
      - "/dev/bus/usb:/dev/bus/usb" 
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"

    group_add:
      - audio
      - video

    volumes:
      - .:/bill_nav
      - /root/.cache/pypoetry:/root/.cache/pypoetry
      - /root/.cache/pip:/root/.cache/pip

      # PulseAudio socket
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native:ro
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie:ro

      # X11 socket (para GUI)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - COQUI_TOS_AGREED=1
