controller_manager:
  ros_parameters:
    update_rate: 50 # Hz
    use_sim_time: true

    # Declare the controllers
    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Parameters for controllers
mecanum_controller:
  ros_parameters:
    publish_rate: 50.0

    odom_frame_id: odom
    base_frame_id: base_footprint

    # Joint names
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "back_right_wheel_joint"
    rear_left_wheel_command_joint_name: "back_left_wheel_joint"

    # Robot physical parameters
    wheel_separation: 0.3
    wheel_radius: 0.1

    use_stamped_vel: true