<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Novos parâmetros do chassi e rodas -->
  <xacro:property name="chassis_length" value="0.5"/>
  <xacro:property name="chassis_width" value="0.3"/>
  <xacro:property name="chassis_height" value="1.17"/>
  <xacro:property name="chassis_mass" value="22.2"/>
  <xacro:property name="wheel_radius" value="0.07"/>
  <xacro:property name="wheel_thickness" value="0.05"/> 
  <xacro:property name="wheel_mass" value="0.2"/>
  <xacro:property name="wheel_offset_x" value="0.2"/>
  <xacro:property name="wheel_offset_y" value="${chassis_width/2 + wheel_thickness/2}"/>
  <xacro:property name="wheel_offset_z" value="0.0"/>

  <!-- Macro do corpo do robô -->
  <xacro:macro name="robot_3d_base" params="prefix">
    <link name="${prefix}base_footprint"/>

    <link name="${prefix}base_link">
      <visual>
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 1"/>
        </material>
        <!-- Centro do chassi fica acima das rodas -->
        <origin xyz="0 0 ${chassis_height/2 + wheel_radius}" rpy="0 0 0"/>
      </visual>

      <collision>
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <origin xyz="0 0 ${chassis_height/2 + wheel_radius}" rpy="0 0 0"/>
      </collision>

      <inertial>
        <origin xyz="0 0 ${chassis_height/2 + wheel_radius}" rpy="0 0 0"/>
        <mass value="${chassis_mass}"/>
        <inertia
          ixx="${(1/12.0) * chassis_mass * (chassis_width * chassis_width + chassis_height * chassis_height)}"
          ixy="0.0"
          ixz="0.0"
          iyy="${(1/12.0) * chassis_mass * (chassis_length * chassis_length + chassis_height * chassis_height)}"
          iyz="0.0"
          izz="${(1/12.0) * chassis_mass * (chassis_length * chassis_length + chassis_width * chassis_width)}"/>
      </inertial>
    </link>

    <gazebo reference="${prefix}base_link">
      <visual>
        <material>
          <ambient>0 0.7 0 1</ambient>
          <diffuse>0 0.7 0 1</diffuse>
          <specular>0 0.7 0 1</specular>
        </material>
      </visual>
    </gazebo>

    <joint name="${prefix}base_joint" type="fixed">
      <parent link="${prefix}base_footprint"/>
      <child link="${prefix}base_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
</robot>
